services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: auth_db,user_db,seller_db,inventory_db,order_db,payment_db,shipping_db,notification_db,wishlist_db,promotion_db,media_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
      - ./infra/postgres/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh
      - ./infra/postgres/init-notification-db.sh:/docker-entrypoint-initdb.d/init-notification-db.sh
      - ./infra/postgres/migrations/notification-service/0001_init.sql:/docker-entrypoint-initdb.d/notification/0001_init.sql
  
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
  
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redisinsightdata:/data
    depends_on:
      - redis
  
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - miniodata:/data

  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -c
      - |
        until mc alias set local http://minio:9000 minioadmin minioadmin; do
          echo "waiting for minio..."; sleep 2;
        done
        mc mb --ignore-existing local/media         
        mc anonymous set download local/media
  
  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_UNTRUSTED_LUA_SANDBOX_REQUIRES: kong.plugins.jwt.jwt_parser
    volumes:
      - ./gateway/kong/kong.yml:/kong/kong.yml
    ports:
      - '8000:8000'
      - '8001:8001'
    depends_on:
      - auth-service
      - user-service
      - notification-service
      - seller-service
      - media-service
      - product-catalog-service
      - inventory-service
      - search-service
      - order-service
      - payment-service
      - promotion-service
      - shipping-service
      - review-service
      - cart-service
      - chat-service
    
  krakend:
    image: krakend:2.13.8
    volumes:
      - ./gateway/krakend/krakend.json:/etc/krakend/krakend.json
    ports:
      - "8090:8080"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  
  kafka:
    image: apache/kafka:4.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafkadata:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "bash", "-c", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  kafka-init:
    image: apache/kafka:4.1.0
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./infra/kafka/create-topics.sh:/create-topics.sh:ro
    entrypoint: [ "/bin/bash", "/create-topics.sh" ]
  
  akhq:
    image: tchiotludo/akhq:latest
    ports:
      - "8082:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:9092"            
  
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Database=auth_db;Username=root;Password=root
      Jwt__Issuer: https://auth.shopee.com
      Jwt__Audience: shopee-api
      Jwt__AccessTokenExpirationMinutes: 15
      Jwt__PrivateKeyPath: /app/keys/jwt-private.pem
      Jwt__KeyId: auth-key-2026-07
      Redis__ConnectionString: redis:6379
      Kafka__BootstrapServers: kafka:9092
    volumes:
      - ./services/auth-service/keys:/app/keys:ro
    ports:
      - '5001:8080'
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Database=user_db;Username=root;Password=root
      Kafka__BootstrapServers: kafka:9092
    ports:
      - '5002:8080'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  seller-service:
    build:
      context: .
      dockerfile: services/seller-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Database=seller_db;Username=root;Password=root
      Kafka__BootstrapServers: kafka:9092
    ports:
      - '5003:8080'
      - '6003:8081'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://root:root@postgres:5432/notification_db
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: notification-service
      KAFKA_GROUP_ID: notification-service-group
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
    ports:
      - '5006:3000'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  media-service:
    build:
      context: .
      dockerfile: services/media-service/Dockerfile
      target: runtime
    environment:
      PORT: 8080
      DATABASE_URL: postgres://root:root@postgres:5432/media_db?sslmode=disable
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: media
      MINIO_USE_SSL: "false"
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: media-events
      KAFKA_PRODUCT_MEDIA_ATTACHED_TOPIC: product-catalog.product-media-attached.v1
      KAFKA_PRODUCT_MEDIA_ATTACHED_GROUP_ID: media-service-group
      MINIO_PUBLIC_ENDPOINT: localhost:9000
      MINIO_PUBLIC_USE_SSL: "false"
    ports:
      - '5007:8080'
    depends_on:
      media-migrate:
        condition: service_completed_successfully
      minio-init:
        condition: service_completed_successfully
      kafka-init:
        condition: service_completed_successfully

  media-migrate:
    build:
      context: .
      dockerfile: services/media-service/Dockerfile
      target: migrate
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/media_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_started
    command: [ "up" ]
  
  product-catalog-service:
    build:
      context: .
      dockerfile: services/product-catalog-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: mongodb://mongo:27017/product_catalog_db
      Kafka__BootstrapServers: kafka:9092
    ports:
      - '5004:8080'
    depends_on:
      mongo:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
  
  inventory-service:
    build:
      context: .
      dockerfile: services/inventory-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Database=inventory_db;Username=root;Password=root
      Kafka__BootstrapServers: kafka:9092
    ports:
      - '5005:8080'
      - '6005:8081'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
  
  search-service:
    build:
      context: .
      dockerfile: services/search-service/Dockerfile
      target: runtime
    environment:
      ES_URL: http://elasticsearch:9200
      ES_INDEX: product_listings
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: product-catalog.product-listing-view-updated.v1
      KAFKA_GROUP_ID: search-service-group
      REDIS_ADDR: redis:6379
      PORT: 8080
    ports:
      - '5008:8080'
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=order_db;Username=root;Password=root
      Kafka__BootstrapServers: kafka:9092
      Services__ShopGrpc: http://seller-service:8081
      Services__InventoryGrpc: http://inventory-service:8081
      Services__PromotionGrpc: http://promotion-service:8081
      Services__ShippingGrpc: http://shipping-service:8081
    ports:
      - '5009:8080'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=payment_db;Username=root;Password=root
      Kafka__BootstrapServers: kafka:9092
      VnPay__TmnCode: ${VNPAY_TMN_CODE}
      VnPay__HashSecret: ${VNPAY_HASH_SECRET}
      VnPay__PaymentBaseUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      VnPay__ReturnUrl: ${VNPAY_RETURN_URL}
    ports:
      - '5010:8080'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  promotion-service:
    build:
      context: .
      dockerfile: services/promotion-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=promotion_db;Username=root;Password=root
      Kafka__BootstrapServers: kafka:9092
    ports:
      - '5011:8080'
      - '6011:8081'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

  shipping-service:
    build:
      context: .
      dockerfile: services/shipping-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=shipping_db;Username=root;Password=root
      Kafka__BootstrapServers: kafka:9092
    ports:
      - '5012:8080'
      - '6012:8081'
    depends_on:
      postgres:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
  
  review-service:
    build:
      context: .
      dockerfile: services/review-service/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: mongodb://mongo:27017/review_db
      Kafka__BootstrapServers: kafka:9092
    ports:
      - '5013:8080'
    depends_on:
      mongo:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully
  
  cart-service:
    build:
      context: .
      dockerfile: services/cart-service/Dockerfile
      target: runtime
    environment:
      REDIS_ADDR: redis:6379
      PORT: 8080
    ports:
      - '5014:8080'
    depends_on:
      redis:
        condition: service_started
  
  chat-service:
    build:
      context: .
      dockerfile: services/chat-service/Dockerfile
      target: runtime
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: chat_db
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC_MESSAGE_SENT: chat.message-sent.v1
      PORT: 8080
    ports:
      - '5015:8080'
    depends_on:
      mongo:
        condition: service_started
      kafka-init:
        condition: service_completed_successfully

volumes:
  pgdata:
  kafkadata:
  mongodata:
  miniodata:
  redisinsightdata:
  esdata:
  redisdata: