// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SellerService.Domain.Common;
using SellerService.Infrastructure.Data;

#nullable disable

namespace SellerService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260813051315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SellerService.Domain.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsLinkedToMainAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_linked_to_main_account");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("PickupAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_address_id");

                    b.Property<AddressSnapshot>("PickupAddressSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pickup_address_snapshot");

                    b.Property<string>("ShopAvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("shop_avatar_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("PendingSetup")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("account_holder");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_bank_accounts", (string)null);
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopChatQuickReply", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_chat_quick_replies", (string)null);
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopChatSetting", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<bool>("AutoReplyEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_reply_enabled");

                    b.Property<string>("AutoReplyMessage")
                        .HasColumnType("text")
                        .HasColumnName("auto_reply_message");

                    b.Property<bool>("AwayModeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("away_mode_enabled");

                    b.HasKey("ShopId");

                    b.ToTable("shop_chat_settings", (string)null);
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopPaymentSetting", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("PayoutCycle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Weekly")
                        .HasColumnName("payout_cycle");

                    b.HasKey("ShopId");

                    b.ToTable("shop_payment_settings", (string)null);
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopShippingCarrierConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carrier_code");

                    b.Property<Guid>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("connected_at");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ShopId", "CarrierId")
                        .IsUnique();

                    b.ToTable("shop_shipping_carrier_connections", (string)null);
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopVacationSetting", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("ShopId");

                    b.ToTable("shop_vacation_settings", (string)null);
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopBankAccount", b =>
                {
                    b.HasOne("SellerService.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopBankAccounts")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopChatQuickReply", b =>
                {
                    b.HasOne("SellerService.Domain.Entities.Shop", "Shop")
                        .WithMany("ShopChatQuickReplies")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopChatSetting", b =>
                {
                    b.HasOne("SellerService.Domain.Entities.Shop", "Shop")
                        .WithOne("ShopChatSetting")
                        .HasForeignKey("SellerService.Domain.Entities.ShopChatSetting", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopPaymentSetting", b =>
                {
                    b.HasOne("SellerService.Domain.Entities.Shop", "Shop")
                        .WithOne("ShopPaymentSetting")
                        .HasForeignKey("SellerService.Domain.Entities.ShopPaymentSetting", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopShippingCarrierConnection", b =>
                {
                    b.HasOne("SellerService.Domain.Entities.Shop", "Shop")
                        .WithMany("ShippingCarrierConnections")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("SellerService.Domain.Entities.ShopVacationSetting", b =>
                {
                    b.HasOne("SellerService.Domain.Entities.Shop", "Shop")
                        .WithOne("ShopVacationSetting")
                        .HasForeignKey("SellerService.Domain.Entities.ShopVacationSetting", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("SellerService.Domain.Entities.Shop", b =>
                {
                    b.Navigation("ShippingCarrierConnections");

                    b.Navigation("ShopBankAccounts");

                    b.Navigation("ShopChatQuickReplies");

                    b.Navigation("ShopChatSetting");

                    b.Navigation("ShopPaymentSetting");

                    b.Navigation("ShopVacationSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
