syntax = "proto3";
option csharp_namespace = "Common.Contracts.Grpc.Shipping";
package shipping;

service ShippingGrpcService {
  rpc CalculateFee (CalculateFeeRequest) returns (CalculateFeeResponse);
}

message ShippingFeeItem {
  int32 quantity = 1;
  int32 weight_gram = 2;
  int32 length = 3;
  int32 width = 4;
  int32 height = 5;
}

message CalculateFeeRequest {
  string carrier_code = 1;
  string pickup_province = 2;
  string pickup_ward = 3;
  string delivery_province = 4;
  string delivery_ward = 5;
  repeated ShippingFeeItem items = 6;
}

message CalculateFeeResponse {
  bool is_valid = 1;
  int32 fee = 2;
  optional string estimated_start = 3;
  optional string estimated_end = 4;
  optional string failure_reason = 5;
}