syntax = "proto3";
option csharp_namespace = "Common.Contracts.Grpc.Shop";
package shop;

service ShopGrpcService {
  rpc GetPickupAddress (GetPickupAddressRequest) returns (GetPickupAddressResponse);
}

message AddressSnapshot {
  string user_id = 1;
  string full_name = 2;
  string phone = 3;
  string province = 4;
  string ward = 5;
  string address_detail = 6;
  string full_address_text = 7;
  optional string latitude = 8;
  optional string longitude = 9;
  string address_type = 10;
}

message GetPickupAddressRequest {
  string shop_id = 1;
}

message GetPickupAddressResponse {
  bool is_valid = 1;
  AddressSnapshot pickup_address_snapshot = 2;
  optional string failure_reason = 3;
  string shop_name = 4;
}