// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/search": {
            "get": {
                "tags": [
                    "search"
                ],
                "summary": "Full-text search products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "minimum price",
                        "name": "priceMin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "maximum price",
                        "name": "priceMax",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category id",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "price|rating|soldCount, append :asc or :desc, e.g. price:asc",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "items per page",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.SearchResponse"
                        }
                    }
                }
            }
        },
        "/search/suggest": {
            "get": {
                "tags": [
                    "search"
                ],
                "summary": "Autocomplete product name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "prefix to suggest against",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.SuggestResponse"
                        }
                    }
                }
            }
        },
        "/search/trending": {
            "get": {
                "tags": [
                    "search"
                ],
                "summary": "Top trending search keywords",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "number of keywords to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.TrendingResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CategoryPathItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.ProductListing": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "categoryPath": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CategoryPathItem"
                    }
                },
                "description": {
                    "type": "string"
                },
                "discountPercent": {
                    "type": "integer"
                },
                "isOutOfStock": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "originalPriceMin": {
                    "type": "string",
                    "example": "0"
                },
                "priceMax": {
                    "type": "string",
                    "example": "0"
                },
                "priceMin": {
                    "type": "string",
                    "example": "0"
                },
                "productId": {
                    "type": "string"
                },
                "ratingAverage": {
                    "type": "number"
                },
                "ratingCount": {
                    "type": "integer"
                },
                "searchableSpecs": {
                    "type": "string"
                },
                "shopId": {
                    "type": "string"
                },
                "shopName": {
                    "type": "string"
                },
                "soldCount": {
                    "type": "integer"
                },
                "stockTotal": {
                    "type": "integer"
                },
                "syncedAt": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnailUrl": {
                    "type": "string"
                }
            }
        },
        "http.SearchResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductListing"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "http.SuggestResponse": {
            "type": "object",
            "properties": {
                "suggestions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "http.TrendingItem": {
            "type": "object",
            "properties": {
                "keyword": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "http.TrendingResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.TrendingItem"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Search Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
