// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Get full cart grouped by shop",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/application.ShopCartGroup"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "cart"
                ],
                "summary": "Clear the entire cart (used after checkout succeeds)",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/cart/items": {
            "post": {
                "description": "If combinationId already exists in the cart, quantity is added on top of the existing quantity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Add item to cart",
                "parameters": [
                    {
                        "description": "item to add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.AddItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Remove multiple items from cart at once",
                "parameters": [
                    {
                        "description": "combination ids to remove",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.RemoveItemsRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/cart/items/{combinationId}": {
            "delete": {
                "tags": [
                    "cart"
                ],
                "summary": "Remove one item from cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "combination id",
                        "name": "combinationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Update item quantity or selection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "combination id",
                        "name": "combinationId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application.UpdateItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cart/selected-summary": {
            "get": {
                "description": "priceSnapshot is intentionally omitted from this response — Order Service always re-fetches real price from Inventory Service at checkout.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Get selected items grouped by shop, for building CheckoutCommand",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/application.ShopCheckoutInfo"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "application.AddItemRequest": {
            "type": "object",
            "properties": {
                "combinationId": {
                    "type": "string"
                },
                "isSelected": {
                    "type": "boolean"
                },
                "priceSnapshot": {
                    "type": "integer"
                },
                "productId": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "shippingInfo": {
                    "$ref": "#/definitions/domain.ShippingInfo"
                },
                "shopId": {
                    "type": "string"
                },
                "shopName": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "variation": {
                    "type": "string"
                }
            }
        },
        "application.CartItemResponse": {
            "type": "object",
            "properties": {
                "addedAt": {
                    "type": "string"
                },
                "combinationId": {
                    "type": "string"
                },
                "isSelected": {
                    "type": "boolean"
                },
                "priceSnapshot": {
                    "type": "integer"
                },
                "productId": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "shopId": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "variation": {
                    "type": "string"
                }
            }
        },
        "application.CheckoutItem": {
            "type": "object",
            "properties": {
                "combinationId": {
                    "type": "string"
                },
                "priceSnapshot": {
                    "type": "integer"
                },
                "productId": {
                    "type": "string"
                },
                "productName": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "shippingInfo": {
                    "$ref": "#/definitions/domain.ShippingInfo"
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "variation": {
                    "type": "string"
                }
            }
        },
        "application.RemoveItemsRequest": {
            "type": "object",
            "properties": {
                "combinationIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "application.ShopCartGroup": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/application.CartItemResponse"
                    }
                },
                "shopId": {
                    "type": "string"
                },
                "shopName": {
                    "type": "string"
                }
            }
        },
        "application.ShopCheckoutInfo": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/application.CheckoutItem"
                    }
                },
                "shopId": {
                    "type": "string"
                },
                "shopName": {
                    "type": "string"
                }
            }
        },
        "application.UpdateItemRequest": {
            "type": "object",
            "properties": {
                "isSelected": {
                    "type": "boolean"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.Dimensions": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "number"
                },
                "length": {
                    "type": "number"
                },
                "width": {
                    "type": "number"
                }
            }
        },
        "domain.ShippingInfo": {
            "type": "object",
            "properties": {
                "dimensions": {
                    "$ref": "#/definitions/domain.Dimensions"
                },
                "weightGrams": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Cart Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
