// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromotionService.Infrastructure.Data;

#nullable disable

namespace PromotionService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260823085351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "CreatedAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Common.Outbox.ProcessedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventType");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.FlashSaleCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Scheduled")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("flash_sale_campaigns", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.FlashSaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CombinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("combination_id");

                    b.Property<int>("DiscountedPrice")
                        .HasColumnType("integer")
                        .HasColumnName("discounted_price");

                    b.Property<int?>("QuantityLimit")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_limit");

                    b.Property<int>("QuantitySold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity_sold");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CombinationId");

                    b.ToTable("flash_sale_items", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.QuantityDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.ToTable("quantity_discounts", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int?>("DiscountAmount")
                        .HasColumnType("integer")
                        .HasColumnName("discount_amount");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ends_at");

                    b.Property<int?>("MaxDiscountAmount")
                        .HasColumnType("integer")
                        .HasColumnName("max_discount_amount");

                    b.Property<int>("MinOrderValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("min_order_value");

                    b.Property<int?>("QuantityLimit")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_limit");

                    b.Property<int>("QuantityUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity_used");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("starts_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.VoucherRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("integer")
                        .HasColumnName("discount_amount");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId", "OrderId")
                        .IsUnique();

                    b.ToTable("voucher_redemptions", (string)null);
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.FlashSaleItem", b =>
                {
                    b.HasOne("PromotionService.Domain.Entities.FlashSaleCampaign", "FlashSaleCampaign")
                        .WithMany("FlashSaleItems")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashSaleCampaign");
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.VoucherRedemption", b =>
                {
                    b.HasOne("PromotionService.Domain.Entities.Voucher", "Voucher")
                        .WithMany("VoucherRedemptions")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.FlashSaleCampaign", b =>
                {
                    b.Navigation("FlashSaleItems");
                });

            modelBuilder.Entity("PromotionService.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("VoucherRedemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
